version: '3'
services:

  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: portainer
    ports:
      - "9000:9000"
    networks:
      - back
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data

  web:
    build: './web'
    ports:
      - "3000:3000"

  search:
    build: './search'
    ports:
      - "3001:3001"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  books:
    build: './books'
    ports:
      - "3002:3002"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  videos:
    build: './videos'
    ports:
      - "3003:3003"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
      
  db:
    image: mongo
    ports:
      - "27017:27017"

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - books
      - search
      - videos

volumes:
  portainerdata: